### ISSUE TITLE
Better error reporting for t-sparqlUpdate

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#206]
When you debug a pipeline and it fails due to an error caused by the t-sparqlUpdate DPU, the reported error message is of little use, because the concrete error message is swallowed and replaced by a generic and uninformative message, such as `Caused by: eu.unifiedviews.dpu.DPUException: Problem with query`. This makes debugging pipelines more difficult than it needs to be. It would be better if the original error message was shown to give the pipeline creator more information about the error.

**Comment by tomas-knap** [comment]
Discussed with Martin Necasky and approved by him

**Comment by tomas-knap** [comment]
Solved in https://github.com/UnifiedViews/Plugins/pull/209, please retest and if you are satisfied, close.

**Comment by jindrichmynarz** [comment]
I'm using 05ab9fc2f39870b9f15931edad3d5f12f272632f and the error reporting is still missing. Is it possible that it was left out in the merge?

**Comment by tomas-knap** [comment]
@skodape Please discuss with @jindrichmynarz and solve

**Comment by skodape** [comment]
@jindrichmynarz Do we have public instance where I can take a look on execution log, event .. etc .. with this DPU, where it does not work?

**Comment by jindrichmynarz** [comment]
Restarting UV back-end makes the updated DPU work as expected.
